[package]
name = "day1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "part_1"
path = "src/part_1/main.rs"

[[bin]]
name = "part_2"
path = "src/part_2/main.rs"

[dependencies]
